---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php support
    package:                                    # is generic OS package manager in ansible 
      name: 
        - "{{apache-package}}"
        - "{{php-package}}"        
      state: latest
      update_cache: yes
